colors:
  primary:
    background:        &background '#1c1c1c'
    foreground:        '#e8bc9b'
    bright_foreground: '#ddb89b'
    dim_foreground:    '#a89984'
  cursor:
    text:   CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text:   CellBackground
    cursor: CellForeground
    search:
      matches:
        foreground: '#000000'
        background: '#ffffff'
      focused_match:
       foreground: CellBackground
       background: CellForeground
      bar:
        background: ''
        foreground: ''
    line_indicator:
      foreground: None
      background: None
  selection:
    text:       CellBackground
    background: CellForeground
  bright:
    black:   '#424242'
    red:     '#e86161'
    green:   '#81d383'
    yellow:  '#fabd2f'
    blue:    '#5a8fb5'
    magenta: '#d3869b'
    cyan:    '#6dbaad'
    white:   '#efb49b'
  normal:
    black:   '#1c1c1c'
    red:     '#db3232'
    green:   '#6fba72'
    yellow:  '#ce9c37'
    blue:    '#2176b2'
    magenta: '#b16286'
    cyan:    '#21b29a'
    white:   '#af9c80'

font:
  normal:
    family: JetBrains Mono Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: JetBrains Mono Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: JetBrains Mono Nerd Font
    style: Italic

  # Bold italic font face
  bold_italic:
    family: JetBrains Mono Nerd Font
    style: Bold Italic

  # Point size
  size: 11

window:
  padding:
    x: 10
    y: 10
