[colors.bright]
black = "#353535"
blue = "#5a8fb5"
cyan = "#81d383"
green = "#81d383"
magenta = "#d3869b"
red = "#e86161"
white = "#efb49b"
yellow = "#fabd2f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#353535"
blue = "#2176b2"
cyan = "#6fba72"
green = "#6fba72"
magenta = "#b16286"
red = "#db3232"
white = "#af9c80"
yellow = "#ce9c37"

[colors.primary]
background = "#0b0b0b"
bright_foreground = "#ccdafc"
dim_foreground = "#ccdafc"
foreground = "#d8c097"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[font]
size = 11

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydidaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[window.padding]
x = 15
y = 15
